# Generated by Django 4.1.7 on 2023-05-27 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import futbik.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championships',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=1990, verbose_name='Начало чемпионата')),
                ('end_year', models.IntegerField(default=1990, verbose_name='Конец чемпионата')),
                ('name', models.CharField(default='default_name', max_length=80)),
                ('league', models.CharField(default='', max_length=80)),
                ('country', models.CharField(default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Чемпионат',
                'verbose_name_plural': 'Чемпионаты',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название клуба')),
                ('emblem', models.ImageField(default=None, upload_to='', verbose_name='Эмблема')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', futbik.models.CustomDateTimeField(default=datetime.datetime(1900, 11, 4, 0, 5, 23), verbose_name='Дата и время проведения')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship', to='futbik.championships', verbose_name='Чемпионат')),
                ('teams', models.ManyToManyField(related_name='teams', to='futbik.clubs', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='futbik.clubs')),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_score', to='futbik.matches')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счет',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('club', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='club_players', to='futbik.clubs')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='futbik.clubs')),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='futbik.matches')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='futbik.players')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Составы',
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xPos', models.FloatField(default=None, verbose_name='X')),
                ('yPos', models.FloatField(default=None, verbose_name='Y')),
                ('distance', models.FloatField(default=None, verbose_name='Расстояние')),
                ('isGoal', models.BooleanField(default=False, verbose_name='Гол')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbik.lineup')),
            ],
            options={
                'verbose_name': 'Удар',
                'verbose_name_plural': 'Удары',
            },
        ),
    ]
