# Generated by Django 4.1.7 on 2023-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbik', '0003_alter_lineup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='is_first_eleven',
            field=models.BooleanField(default=False),
        ),
    ]
