# Generated by Django 4.1.7 on 2023-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbik', '0005_lineup_position_players_height_players_shirtno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='surname',
            field=models.CharField(default='', max_length=80),
        ),
    ]
