# Generated by Django 4.1.7 on 2023-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbik', '0008_hit_pg_alter_hit_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='angle',
            field=models.FloatField(default=None, verbose_name='Угол'),
        ),
        migrations.AddField(
            model_name='hit',
            name='footed',
            field=models.CharField(default=None, max_length=6, verbose_name='footed'),
        ),
        migrations.AddField(
            model_name='hit',
            name='passes_before',
            field=models.IntegerField(default=None, verbose_name='Пасы до удара'),
        ),
        migrations.AddField(
            model_name='hit',
            name='shooted_by',
            field=models.CharField(default=None, max_length=15, verbose_name='Чем ударил'),
        ),
        migrations.AddField(
            model_name='hit',
            name='shots_before',
            field=models.IntegerField(default=None, verbose_name='Удары до удара'),
        ),
        migrations.AddField(
            model_name='hit',
            name='shots_by_team_before',
            field=models.IntegerField(default=None, verbose_name='Удары всей команды до удара'),
        ),
    ]
