# Generated by Django 4.1.7 on 2023-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbik', '0010_alter_hit_angle_alter_hit_footed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='angle',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Угол'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='footed',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='footed'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='passes_before',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Пасы до удара'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shooted_by',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Чем ударил'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shots_before',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Удары до удара'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shots_by_team_before',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Удары всей команды до удара'),
        ),
    ]
