# Generated by Django 4.1.7 on 2023-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbik', '0011_alter_hit_angle_alter_hit_footed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='angle',
            field=models.FloatField(default=90, verbose_name='Угол'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='footed',
            field=models.CharField(default='right', max_length=6, verbose_name='footed'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='passes_before',
            field=models.IntegerField(default=0, verbose_name='Пасы до удара'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shooted_by',
            field=models.CharField(default='Head', max_length=15, verbose_name='Чем ударил'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shots_before',
            field=models.IntegerField(default=0, verbose_name='Удары до удара'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='shots_by_team_before',
            field=models.IntegerField(default=0, verbose_name='Удары всей команды до удара'),
        ),
    ]
